export enum SOCKET_EVENT {
  MESSAGE = `MESSAGE`,
  SEND_MESSAGE = `SEND_MESSAGE`,
  CREATE_ROOM = `CREATE_ROOM`,
  JOIN_ROOM = `JOIN_ROOM`,
  LEAVE_ROOM = `LEAVE_ROOM`,
  DELETE_ROOM = `DELETE_ROOM`,
  MESSAGE_SENT = `MESSAGE_SENT`,
  MESSAGE_RECEIVED = `MESSAGE_RECEIVED`,
  USER_JOINED = `USER_JOINED`,
  USER_LEFT = `USER_LEFT`,
}
